FROM golang:1.24-alpine

WORKDIR /app

# Install git and required build tools
RUN apk add --no-cache git gcc musl-dev

# Copy module dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Expose control plane API port
EXPOSE ${PORT}

CMD ["go", "run", "cmd/server/main.go"]
